api:
  versions:
    v1: v1
server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-service/codster_db?useSSL=false
    password: kLGa2e8vfngD4Qy5s9mRhA3UB
    username: develop
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations:
      - "classpath:/database/migrations"
      - "classpath:/database/seeders"
    out-of-order: true
    table: migrations
    url: ${spring.datasource.url}
    user: root